### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by Wuyuan5O** [silie666/bilibiliLottery#1]
应该要配置我的账号把。
我安装了go环境后直接在cmd上面跑就可以吗

**Comment by silie666** [comment]
> 应该要配置我的账号把。
> 我安装了go环境后直接在cmd上面跑就可以吗

config里面的bilibili.go，修改cookie之后，还有一个参数是ANIO，跟my，一个是对方的空间的url，这个人必须是一个只转发抽奖动态的人，一个是自己的空间。还要配置一下db文件，配置完mysql之后直接go run就好了

**Comment by valiner** [comment]
咋不打包好，直接做个release

**Comment by silie666** [comment]
> 咋不打包好，直接做个release

因为这是我在学习Go的时候写的，没打算写得太精细😥
