### ISSUE TITLE
关于转盘抽奖

### ISSUE THREAD

**Issue by Dingtianqi329** [silie666/bilibiliLottery#10]
大佬您好，我在运行转盘抽奖是遇到了一个问题，不知道如何解决，想来请教一下您：csrf 校验失败的原因，万分感谢！
<img width="1003" alt="截屏2022-11-03 15 21 57" src="https://user-images.githubusercontent.com/64207276/199666341-619b093f-a1df-4531-a954-cf8170f81039.png">

**Comment by silie666** [comment]
> 大佬您好，我在运行转盘抽奖是遇到了一个问题，不知道如何解决，想来请教一下您：csrf 校验失败的原因，万分感谢！ <img alt="截屏2022-11-03 15 21 57" width="1003" src="https://user-images.githubusercontent.com/64207276/199666341-619b093f-a1df-4531-a954-cf8170f81039.png">

看了一眼啊b好像要换其他方式获取抽奖机会了，目前接口增加抽奖次数只有分享类型是可以的，先观察一段时间

**Comment by silie666** [comment]
报错已解决
