### ISSUE TITLE
关于运行报错/卡住

### ISSUE THREAD

**Issue by MrSnake0208** [silie666/bilibiliLottery#11]
运行环境：Centos7.8
Golang版本：1.19.3
拉取代码版本：最新版本
出现问题：
1.  转盘抽奖运行后显示获取列表失败，但同时我在win10电脑上运行显示csrf校验失败，这个问题应该与上一个issue是一样的问题。
![image](https://user-images.githubusercontent.com/74225450/200118939-f916f184-f796-4497-a11a-b371b5c5a1c0.png)

2. 运行 start后卡死，没有任何报错，没有任何输出
![image](https://user-images.githubusercontent.com/74225450/200118969-30cb6d59-8286-4e73-a079-0b2e57a7343c.png)

**Comment by MrSnake0208** [comment]
后续补充：2卡了几分钟后出现如下报错
`{"err":"添加失败","level":"error","msg":"","start_time":"2022-11-05T21:19:07.596206857+08:00","time":"2022-11-05 21:19:07"}
{"err":"添加失败","level":"error","msg":"","start_time":"2022-11-05T21:19:07.596774959+08:00","time":"2022-11-05 21:19:07"}
time="2022-11-05T21:19:07+08:00" level=error err="添加失败" start_time="2022-11-05 21:19:07.596774959 +0800 CST m=+300.317608700"
{"err":"添加失败","level":"error","msg":"","start_time":"2022-11-05T21:19:07.59715856+08:00","time":"2022-11-05 21:19:07"}
time="2022-11-05T21:19:07+08:00" level=error err="添加失败" start_time="2022-11-05 21:19:07.59715856 +0800 CST m=+300.317992301"
{"err":"添加失败","level":"error","msg":"","start_time":"2022-11-05T21:19:07.597488061+08:00","time":"2022-11-05 21:19:07"}
time="2022-11-05T21:19:07+08:00" level=error err="添加失败" start_time="2022-11-05 21:19:07.597488061 +0800 CST m=+300.318321902"
{"err":"添加失败","level":"error","msg":"","start_time":"2022-11-05T21:19:07.597795362+08:00","time":"2022-11-05 21:19:07"}
time="2022-11-05T21:19:07+08:00" level=error err="添加失败" start_time="2022-11-05 21:19:07.597795362 +0800 CST m=+300.318629103"
{"err":"添加失败","level":"error","msg":"","start_time":"2022-11-05T21:19:07.598154264+08:00","time":"2022-11-05 21:19:07"}
time="2022-11-05T21:19:07+08:00" level=error err="添加失败" start_time="2022-11-05 21:19:07.598154264 +0800 CST m=+300.318988005"
{"err":"添加失败","level":"error","msg":"","start_time":"2022-11-05T21:19:07.598448465+08:00","time":"2022-11-05 21:19:07"}
time="2022-11-05T21:19:07+08:00" level=error err="添加失败" start_time="2022-11-05 21:19:07.598448465 +0800 CST m=+300.319282306"
{"err":"添加失败","level":"error","msg":"","start_time":"2022-11-05T21:19:07.598799166+08:00","time":"2022-11-05 21:19:07"}
time="2022-11-05T21:19:07+08:00" level=error err="添加失败" start_time="2022-11-05 21:19:07.598799166 +0800 CST m=+300.319632907"
{"err":"添加失败","level":"error","msg":"","start_time":"2022-11-05T21:19:07.599110567+08:00","time":"2022-11-05 21:19:07"}
time="2022-11-05T21:19:07+08:00" level=error err="添加失败" start_time="2022-11-05 21:19:07.599110567 +0800 CST m=+300.319944408"
{"err":"添加失败","level":"error","msg":"","start_time":"2022-11-05T21:19:07.599429068+08:00","time":"2022-11-05 21:19:07"}
time="2022-11-05T21:19:07+08:00" level=error err="添加失败" start_time="2022-11-05 21:19:07.599429068 +0800 CST m=+300.320262809"
{"err":"添加失败","level":"error","msg":"","start_time":"2022-11-05T21:19:07.59979207+08:00","time":"2022-11-05 21:19:07"}
time="2022-11-05T21:19:07+08:00" level=error err="添加失败" start_time="2022-11-05 21:19:07.59979207 +0800 CST m=+300.320625811"
{"err":"添加失败","level":"error","msg":"","start_time":"2022-11-05T21:19:07.600143671+08:00","time":"2022-11-05 21:19:07"}
time="2022-11-05T21:19:07+08:00" level=error err="添加失败" start_time="2022-11-05 21:19:07.600143671 +0800 CST m=+300.320977512"
`

**Comment by silie666** [comment]
> 运行环境：Centos7.8 Golang版本：1.19.3 拉取代码版本：最新版本 出现问题：
> 
> 1. 转盘抽奖运行后显示获取列表失败，但同时我在win10电脑上运行显示csrf校验失败，这个问题应该与上一个issue是一样的问题。
>    ![image](https://user-images.githubusercontent.com/74225450/200118939-f916f184-f796-4497-a11a-b371b5c5a1c0.png)
> 2. 运行 start后卡死，没有任何报错，没有任何输出
>    ![image](https://user-images.githubusercontent.com/74225450/200118969-30cb6d59-8286-4e73-a079-0b2e57a7343c.png)

第一个问题已解决（csrf失败是那个活动不支持通用接口获取抽奖次数，有空再看看这个活动是什么情况），第二个问题是爬取动态和转发动态都是不同时间定时执行的，默认5分钟/43分钟，可以在配置文件中改，添加失败的原因是已经有相同的记录再数据库了，这个可以不用管

**Comment by MrSnake0208** [comment]
谢谢！！更改了之后可以正常运行了！！
