### ISSUE TITLE
青龙问题

### ISSUE THREAD

**Issue by bingtaisanbuqu** [silie666/bilibiliLottery#13]
请问拉库命令是多少，想要布置在青龙运行，感谢大佬

**Comment by Eric166904861** [comment]
没适配青龙吧，青龙里的脚本用go和sql的基本没有吧

**Comment by silie666** [comment]
> 请问拉库命令是多少，想要布置在青龙运行，感谢大佬

没有用过青龙🤔，有空研究看看

**Comment by yao52069** [comment]
请问拉库命令是多少，想要布置在青龙运行，感谢大佬
