### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by llx-08** [silie666/bilibiliLottery#14]
扫码登录由于二维码是输出在Terminal无法登录，复制链接到手机上会显示已经过期😢

**Comment by silie666** [comment]
> 扫码登录由于二维码是输出在Terminal无法登录，复制链接到手机上会显示已经过期😢

🤔登录二维码确实是输出在Terminal，我刚刚试着用手机打开链接发现app连确认登录界面都没弹出了，但用app扫描二维码又能正常弹出，扫出来的内容也和登录链接一致，不知道是不是app更新了的原因

**Comment by silie666** [comment]
b站的app问题，已经可以正常登录
