### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by jiuyuan233** [silie666/bilibiliLottery#15]
能出一个图文教程吗小白实在不会

**Comment by silie666** [comment]
> 能出一个图文教程吗小白实在不会

简介写得很清楚吧，你是哪里不会？🤔

**Comment by jiuyuan233** [comment]
感谢你能给我解答，里面的mysql-name数据库名称不知道怎么填

**Comment by jiuyuan233** [comment]
> > 能出一个图文教程吗小白实在不会
> 
> 简介写得很清楚吧，你是哪里不会？🤔

感谢你能给我解答，里面的mysql-name数据库名称不知道怎么填
![`HX (UN0R{4SJ4(OFWCJ_6J](https://user-images.githubusercontent.com/119844446/205595498-fadc8e26-2a72-4aab-87ba-b6a42e9b9ab3.png)

**Comment by silie666** [comment]
> > > 能出一个图文教程吗小白实在不会
> > 
> > 
> > 简介写得很清楚吧，你是哪里不会？🤔
> 
> 感谢你能给我解答，里面的mysql-name数据库名称不知道怎么填 ![`HX (UN0R{4SJ4(OFWCJ_6J](https://user-images.githubusercontent.com/119844446/205595498-fadc8e26-2a72-4aab-87ba-b6a42e9b9ab3.png)

需要自己安装mysql数据库

**Comment by jiuyuan233** [comment]
配置文件里还有一些简介中没有出现的内容
![M~S37FE3_JMQ4{S3}UK77O2](https://user-images.githubusercontent.com/119844446/205596706-469da3fa-0ca8-4b39-8061-862f498a3fed.png)

**Comment by silie666** [comment]
> 配置文件里还有一些简介中没有出现的内容 ![M~S37FE3_JMQ4{S3}UK77O2](https://user-images.githubusercontent.com/119844446/205596706-469da3fa-0ca8-4b39-8061-862f498a3fed.png)

简介中没有出现的内容都不需要更改，默认即可

**Comment by jiuyuan233** [comment]
我这还是不行能帮忙看看是什么情况吗
![E2 BY0M5ZH{28QS6NN5P_O4](https://user-images.githubusercontent.com/119844446/205610497-5d8fb11d-fa1e-43f6-a76b-00506b214249.png)

**Comment by jiuyuan233** [comment]
运行到这一步了然后就卡住不动了
![image](https://user-images.githubusercontent.com/119844446/205651843-749b6405-c4bf-4ba1-8847-aefa2e05ae39.png)

**Comment by jiuyuan233** [comment]
这也没添加啊是什么情况
![image](https://user-images.githubusercontent.com/119844446/205655412-ae92c1db-652f-4d5e-8c95-faf935bac4fe.png)

**Comment by jiuyuan233** [comment]
这报错该怎么解决
![image](https://user-images.githubusercontent.com/119844446/205662182-f99f036e-6cf5-40cf-8bb5-a6ad8b82fa2b.png)

**Comment by silie666** [comment]
> 这报错该怎么解决 ![image](https://user-images.githubusercontent.com/119844446/205662182-f99f036e-6cf5-40cf-8bb5-a6ad8b82fa2b.png)

数据库字符集不对，是utfm8b4吗？

**Comment by jiuyuan233** [comment]
抱歉啊我不知道utfmb4是什么我这个是用的电脑自带的cmd添加了go的环境运行的

**Comment by jiuyuan233** [comment]
> 抱歉啊我不知道utfmb4是什么我这个是用的电脑自带的cmd添加了go的环境运行的

我先自己百度一下

**Comment by silie666** [comment]
> > 这报错该怎么解决 ![image](https://user-images.githubusercontent.com/119844446/205662182-f99f036e-6cf5-40cf-8bb5-a6ad8b82fa2b.png)
> 
> 数据库编码不对，是utfm8b4吗？

**Comment by silie666** [comment]
> > 抱歉啊我不知道utfmb4是什么我这个是用的电脑自带的cmd添加了go的环境运行的
> 
> 我先自己百度一下

![image](https://user-images.githubusercontent.com/38691833/205780654-caf9968f-6ad0-4ea1-aaaf-3e11e037c89b.png)

**Comment by jiuyuan233** [comment]
这是会是网络问题吗
![image](https://user-images.githubusercontent.com/119844446/205794049-6e718f0d-80e1-446a-9d84-31616aa6ff16.png)

**Comment by jiuyuan233** [comment]
> 

![image](https://user-images.githubusercontent.com/119844446/205794281-538a9e4b-36f7-4331-85a4-e5d7218576e5.png)

**Comment by silie666** [comment]
> 这是会是网络问题吗 ![image](https://user-images.githubusercontent.com/119844446/205794049-6e718f0d-80e1-446a-9d84-31616aa6ff16.png)

日志路径不对，不过这个可以无视，程序没有中断就可以了

**Comment by jiuyuan233** [comment]
> > 这是会是网络问题吗 ![image](https://user-images.githubusercontent.com/119844446/205794049-6e718f0d-80e1-446a-9d84-31616aa6ff16.png)
> 
> 日志路径不对，不过这个可以无视，程序没有中断就可以了

太好了已经在开始转发了谢谢
