### ISSUE TITLE
转发功能运行后卡住不动

### ISSUE THREAD

**Issue by TopYjj** [silie666/bilibiliLottery#3]

**Comment by silie666** [comment]
因为有定时，我一开始写了是5分钟爬一次

**Comment by silie666** [comment]
> _No description provided._

因为有定时，我一开始写了是5分钟爬一次

**Comment by TopYjj** [comment]
> > _No description provided._
> 
> 因为有定时，我一开始写了是5分钟爬一次

方便加个联系方式吗，我自己也用python实现了一个。不是很熟悉go，运行的时候老显示日志错误

**Comment by silie666** [comment]
> 便加个联系方式吗，我自己也用python实现了一个。不是很熟悉go，运行的时候老显示日志错

b站同昵称，那个日志写法win10会报错但可以无视。
