### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by HIKARuRu5** [silie666/bilibiliLottery#4]
你好，我run的时候遇到一些问题想请教一下，b站搜id没有搜到，请问怎么可以联系呢

**Comment by silie666** [comment]
> 你好，我run的时候遇到一些问题想请教一下，b站搜id没有搜到，请问怎么可以联系呢

你去别人的空间链接上不是有别人的id吗

**Comment by HIKARuRu5** [comment]
> > 你好，我run的时候遇到一些问题想请教一下，b站搜id没有搜到，请问怎么可以联系呢
> 
> 你去别人的空间链接上不是有别人的id吗

不是不是，我是说想通过B站联系您来着。我在run的时候会出现failed to initialize database, got error dial tcp 127.0.0.1:3306: connectex: No connection could be made because the target machine actively refused it.
panic: database data source name error: dial tcp 127.0.0.1:3306: connectex: No connection could be made because the target machine actively refused it.
然后就终止了，请问要怎么办呢

**Comment by silie666** [comment]
> > > 你好，我run的时候遇到一些问题想请教一下，b站搜id没有搜到，请问怎么可以联系呢
> > 
> > 
> > 你去别人的空间链接上不是有别人的id吗
> 
> 不是不是，我是说想通过B站联系您来着。我在run的时候会出现failed to initialize database, got error dial tcp 127.0.0.1:3306: connectex: No connection could be made because the target machine actively refused it. panic: database data source name error: dial tcp 127.0.0.1:3306: connectex: No connection could be made because the target machine actively refused it. 然后就终止了，请问要怎么办呢

这个错误是没有连上数据库啊
