### ISSUE TITLE
关于配置的问题

### ISSUE THREAD

**Issue by xcenweb** [silie666/bilibiliLottery#5]
我查看了cookie里面没有`BILIBILI_UID`，但是这个是不是就是用户id的意思？那我直接填用户id？

**Comment by silie666** [comment]
> 我查看了cookie里面没有`BILIBILI_UID`，但是这个是不是就是用户id的意思？那我直接填用户id？

是的

**Comment by xcenweb** [comment]
好的，谢谢😀
