### ISSUE TITLE
小白来提问啦

### ISSUE THREAD

**Issue by ZYYStudyJAVA** [silie666/bilibiliLottery#6]
大佬，请问一下BILIBILI_UID是啥啊，cookie里面没有这个字段啊

**Comment by silie666** [comment]
> 大佬，请问一下BILIBILI_UID是啥啊，cookie里面没有这个字段啊

自己的b站id

**Comment by ZYYStudyJAVA** [comment]
我发现这个接口只能获取目标用户的10条动态，也就只能跟转10条了，有什么好一点的办法可以设置多转发一些吗

**Comment by silie666** [comment]
> 我发现这个接口只能获取目标用户的10条动态，也就只能跟转10条了，有什么好一点的办法可以设置多转发一些吗

这么做是为了不爬过期的数据，所以只转了首页的动态，首页数据更新了，再转

**Comment by ZYYStudyJAVA** [comment]
那可以更新一下接口让他一次多转点吗，50-60条不嫌多

**Comment by silie666** [comment]
> 以更新一下接口让他一次多转点吗，50-60条不嫌

我个人觉得没必要改，你只要一直挂着程序那个人只要转发一条你也会跟着转，很多其他用户下一页基本都是已经过期的抽奖动态

**Comment by comCN6** [comment]
> > 以更新一下接口让他一次多转点吗，50-60条不嫌
> 
> 我个人觉得没必要改，你只要一直挂着程序那个人只要转发一条你也会跟着转，很多其他用户下一页基本都是已经过期的抽奖动态

这个下下来改好后哪里运行啊，大佬

**Comment by silie666** [comment]
> 个下下来改好后哪里运行啊，大

拉取最新的代码

**Comment by comCN6** [comment]
> > 个下下来改好后哪里运行啊，大
> 
> 拉取最新的代码

![image](https://user-images.githubusercontent.com/96321014/193408577-7797b2f1-6b88-4443-a3e3-42042ede4a34.png)
问一下这是什么意思
