### ISSUE TITLE
出现了报错，但是不太懂

### ISSUE THREAD

**Issue by Sailious** [silie666/bilibiliLottery#7]
![image](https://user-images.githubusercontent.com/105737568/183667674-f4fc47e2-00d9-4834-adf3-3918419efcf8.png)
这个是报错界面
![image](https://user-images.githubusercontent.com/105737568/183668581-4ce2cb80-7504-417e-8c97-17ffc1a35501.png)
db.go截图
![IMG_20220809_215818](https://user-images.githubusercontent.com/105737568/183668701-eb48b82a-945a-4172-ad58-3b11012233cd.png)
bilibili.go截图
自己是个小白，很多地方不太明白，还请大佬不吝赐教

**Comment by silie666** [comment]
> ![image](https://user-images.githubusercontent.com/105737568/183667674-f4fc47e2-00d9-4834-adf3-3918419efcf8.png) 这个是报错界面 ![image](https://user-images.githubusercontent.com/105737568/183668581-4ce2cb80-7504-417e-8c97-17ffc1a35501.png) db.go截图 ![IMG_20220809_215818](https://user-images.githubusercontent.com/105737568/183668701-eb48b82a-945a-4172-ad58-3b11012233cd.png) bilibili.go截图 自己是个小白，很多地方不太明白，还请大佬不吝赐教

没有装mysql？

**Comment by 420348264** [comment]
同样的报错 你解决了吗

**Comment by silie666** [comment]
> 同样的报错 你解决了吗

拉取最新的代码
