### ISSUE TITLE
go run main.go -start

### ISSUE THREAD

**Issue by xxxxxy211** [silie666/bilibiliLottery#8]
![image](https://user-images.githubusercontent.com/59924364/194738541-8a63a6e9-23a7-46ed-a9f1-b9f8414508ac.png)
他会一直卡在这个界面
我是win11的系统
请问正常吗，也没有任何的提示。
go run main.go -draw 是正常运行的

**Comment by xxxxxy211** [comment]
![image](https://user-images.githubusercontent.com/59924364/194739509-85dfae70-eb2f-4e93-aa4d-75c11dac5016.png)

运行后变这样的了

**Comment by xxxxxy211** [comment]
有用的，只是有有点怪....

**Comment by silie666** [comment]
建议在linux服务器挂后台跑，win11系统我不用不是很清楚😉
